### PR TITLE
Upgrade to Kibana 4.1.0

### PR DESCRIPTION
**Pull request by redapple**
Note that `balsamiq/docker-kibana` master branch has a problematic commit about Elasticsearch URL (https://github.com/balsamiq/docker-kibana/commit/b3d6bfef47fdf540276cca0174b9ed983ab0d822)

### CODE REVIEW

**Comment by dangra** [comment]
https://github.com/balsamiq/docker-kibana/commit/b3d6bfef47fdf540276cca0174b9ed983ab0d822 is a regression, you already sent a fix for it and balsamiq merged it in the past. Have you complained ?

**Comment by dangra** [comment]
The change was https://github.com/balsamiq/docker-kibana/pull/7

**Comment by redapple** [comment]
Yes

**Comment by redapple** [comment]
@dangra I did not complain (yet)

**Comment by dangra** [comment]
I did in the commit you linked.

**Pull request merged**
